version: '3.9'

services:
    users-service:
        container_name: users-service
        image: teacinema/users-service:dev
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env.production.local
        networks:
            - teacinema

networks:
    teacinema:
        external: true
